name: gloz_flutter_template
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-263.0.dev <3.0.0'

dependencies:
  device_info_plus: ^4.0.1
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_background_service: ^2.1.3
  shared_preferences: ^2.0.15
  firebase_messaging: ^12.0.1
  dio: ^4.0.6
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
